### ISSUE TITLE
EEGMMIDB class has an initialization error

### ISSUE THREAD

**Issue by rushilanirudh** [fnielsen/brede#12]
Hi Finn

Thank you for putting this class together, I was just looking to work with the EEGMMIDB dataset, and came across your code, which looks like it will be very useful for me.

I am however, getting an error when I try to instantiate the EEGMMIDB class --
When I call
```
$ python brede/data/examples/eegmmidb.py
```
```
Traceback (most recent call last):
  File "brede/data/examples/eegmmidb.py", line 55, in <module>
    main(docopt.docopt(__doc__))
  File "brede/data/examples/eegmmidb.py", line 49, in main
    csp_of_two_runs(subject=subject)
  File "brede/data/examples/eegmmidb.py", line 25, in csp_of_two_runs
    eegmmidb = EEGMMIDB()
  File "/Users/anirudh1/anaconda/lib/python2.7/site-packages/brede-0.1.dev0-py2.7.egg/brede/data/eegmmidb.py", line 75, in __init__
    self.data_dir = join(expanduser(config.get('data', 'data_dir')),
  File "/Users/anirudh1/anaconda/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'data'
```

I'm running it on OSX, and have all the dependencies installed. I was able to get through `python setup.py install` with a few warnings but no errors. Any idea how I can work around this?

Thanks!
Rushil

**Comment by fnielsen** [comment]
A configuration is required. This seems not to be documented well. I have a file called `brede.cfg` with the content

```
[data]
data_dir = ~/brede_data
```

**Comment by rushilanirudh** [comment]
Thanks for the prompt response. I was able to get it to run!
